Repository IsyFact/isy-datetime, pull requests merged in 2024-08, with the labels that each got.

#53 feat: IFS-3611 Update pr_agent.yml
  .github/workflows/pr_agent.yml
Labels: configuration changes, Review effort [1-5]: 1

#50 Bugfix: IFS-3731: Publishing Antora Documentation
  .github/workflows/docs_build.yml
  .github/workflows/package.yaml
  .github/workflows/update_antora_version.yml
  isy-datetime-doc/antora-playbook.yml
  isy-datetime-doc/antora.yml
Labels: Bug fix, Enhancement, Review effort [1-5]: 2

#59 chore: IFS-3767: added workflow dispatch for manual trigger
  .github/workflows/maven_dependency_scan.yml
Labels: Enhancement, configuration changes, Review effort [1-5]: 1

#60 fix: IFS-3938 updated maven_deploy_template.yml to v1.5.0
  .github/workflows/maven_build.yml
  .github/workflows/maven_release.yml
Labels: Enhancement, Review effort [1-5]: 1

#62 IFS-3956: Fixed cron schedule, added Antora token
  .github/workflows/maven_dependency_scan.yml
Labels: Bug fix, Enhancement, Review effort [1-5]: 2
